# Generated by Django 5.0.6 on 2024-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userstab_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
    ]
